name: test

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # - name: npm install
      #   working-directory: ./frontend
      #   run: npm i

      # - name: npm build
      #   working-directory: ./frontend
      #   run: npm run build

      # - name: nginx start
      #   run: |
      #     docker rm -f web
      #     docker run -d -p 80:80 -v ./frontend/dist:/usr/share/nginx/html -v ./frontend/default.conf:/etc/nginx/conf.d/default.conf --name web nginx:1.28

      # - name: uv image build
      #   working-directory: ./backend
      #   run: docker build -t uv:1.1 .

      # - name: fastapi run
      #   working-directory: ./backend
      #   run: docker run -d -p 8001:8000 -v .:/workspace --name back uv:1.1

      - name: compose up
        run: |
          docker compose up -d

